POST    error               riders.admin.report_a_ride(string message)
POST    error               riders.admin.report_a_lost_item(string message)
GET     page                riders.admin.load_about_us_page()
GET     page                riders.admin.load_help_menu()
GET     page                riders.admin.load_report_a_ride_form()
GET     page                riders.admin.load_report_a_lost_item_form()
GET     page                riders.admin.load_how_payment_works_page()
GET     page                riders.admin.load_how_do_free_rides_work_page()
GET     page                riders.admin.load_saftey_page()
GET     page                riders.admin.load_policies_page()
GET     page                riders.admin.load_legal_page()
